# Generated by Django 4.0.4 on 2022-05-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0003_tokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
