# Generated by Django 4.0.4 on 2022-05-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0004_delete_tokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
