# Generated by Django 4.0.4 on 2022-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0010_alter_videos_rate_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='rate_length',
            field=models.IntegerField(default=0),
        ),
    ]
