# Generated by Django 4.0.4 on 2022-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0011_alter_videos_rate_alter_videos_rate_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='rate_calc',
            field=models.FloatField(default=0),
        ),
    ]
