# Generated by Django 4.0.4 on 2022-06-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0012_videos_rate_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_videos', to='kleverApp.videos', unique=True),
        ),
    ]
