# Generated by Django 4.0.4 on 2022-06-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0015_remove_videos_rate_remove_videos_rate_calc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratevideo',
            name='rate_calc',
        ),
        migrations.RemoveField(
            model_name='ratevideo',
            name='rate_length',
        ),
    ]
