# Generated by Django 4.0.4 on 2022-06-19 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0019_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='added_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='font',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
