# Generated by Django 4.0.4 on 2022-06-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleverApp', '0021_rename_added_date_article_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
